TASK0:
  name: VQA
  type: VL-classifier
  loss: BCEWithLogitLoss
  task_id: 1
  dataroot: data/VQA
  features_h5path1: data/coco/coco_trainval_resnet101_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 16
  max_region_num: 100
  batch_size: 256
  eval_batch_size: 1024
  train_split: trainval
  val_split: minval
  lr: 0.00004
  num_epoch: 20
TASK1:
  name: VCR_Q-A
  type: VL-logit
  loss: CrossEntropyLoss
  task_id: 6
  dataroot: ../X_VCR
  features_h5path1: VCR_resnet101_faster_rcnn_genome.lmdb
  features_h5path2: VCR_gt_resnet101_faster_rcnn_genome.lmdb
  train_annotations_jsonpath: ../X_VCR/train.jsonl
  val_annotations_jsonpath: ../X_VCR/val.jsonl
  max_seq_length: 60
  max_region_num: 100
  batch_size: 16
  train_split: train
  val_split: val
  lr: 0.00002
  num_epoch: 8
TASK2:
  name: VCR_QA-R
  type: VL-logit
  loss: CrossEntropyLoss
  task_id: 7
  dataroot: ../X_VCR
  features_h5path1: VCR_resnet101_faster_rcnn_genome.lmdb
  features_h5path2: VCR_gt_resnet101_faster_rcnn_genome.lmdb
  train_annotations_jsonpath: ../X_VCR/train.jsonl
  val_annotations_jsonpath: ../VCR/val.jsonl
  max_seq_length: 80
  max_region_num: 100
  batch_size: 16
  train_split: train
  val_split: val
  lr: 0.00002
  num_epoch: 8
TASK3:
  name: RetrievalFlickr30k
  type: VL-logit
  loss: CrossEntropyLoss
  task_id: 9
  dataroot: data/flickr30k
  features_h5path1: data/flickr30k/flickr30k_test_resnet101_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: data/flickr30k/all_data_final_train_2014.jsonline
  val_annotations_jsonpath: data/flickr30k/all_data_final_test_set0_2014.jsonline
  max_seq_length: 30
  max_region_num: 100
  batch_size: 64
  train_split: train
  val_split: val
  lr: 0.00002
  num_epoch: 20
TASK4:
  name: refcoco+
  type: V-logit
  loss: BCEWithLogitLoss
  task_id: 11
  dataroot: data/referExpression
  features_h5path1: data/referExpression/refcoco+_resnet101_faster_rcnn_genome.lmdb
  features_h5path2: data/referExpression/refcoco+_gt_resnet101_faster_rcnn_genome.lmdb
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 20
  max_region_num: 100
  batch_size: 256
  eval_batch_size: 1024
  train_split: train
  val_split: val
  lr: 0.00004
  num_epoch: 20